name: EasyClearChat
main: GamerMJay\EasyClearChat\Main
author: GamerMJay
api: 5.0.0
version: 1.1.1
website: https://github.com/GamerMJay/EasyClearChat

permissions:
  clearchat.use:
    default: op
