# BetterClearChat V1.0.0 by GamerMJay, licensed under Apache License 2.0!


# Messages
command: "clearchat"
description: "ClearChat Command"
no-permission: "§6§lBetterClearChat §r§8» §cyou have no permission!"
run-ingame: "§6§lBetterClearChat §r§8» §crun this command ingame!"
clearchat-succes: "§6§lBetterClearChat §r§8» §eThe chat was emptied by §6{player}"